### ISSUE TITLE
No such file or directory: 'data/train.txt'  OR which step I missed？

### ISSUE THREAD

**Issue by SeekPoint** [pengming617/Intent_Dtection#2]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/text_classification-pengming617$ python3.6 train.py --model_type=textrnn
2019-06-22 12:25:47.455034: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-22 12:25:47.581120: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-22 12:25:47.581509: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 5.84GiB
2019-06-22 12:25:47.581526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-22 12:25:48.175435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-22 12:25:48.175469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-06-22 12:25:48.175477: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-06-22 12:25:48.175684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5616 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    train.trainModel(embedding_dim, dropout_keep_prob, hidden_num, hidden_size, l2_reg_lambda)
  File "/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/text_classification-pengming617/model/textrnn/TrainModel.py", line 32, in trainModel
    articles, tags = processing.loadPracticeFile('data/train.txt')
  File "/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/text_classification-pengming617/model/textrnn/Processing.py", line 19, in loadPracticeFile
    with open(filename, 'r', encoding='utf-8') as fr:
FileNotFoundError: [Errno 2] No such file or directory: 'data/train.txt'
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/text_classification-pengming617$ python3.6 train.py --model_type=han
2019-06-22 12:27:04.491416: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-22 12:27:04.613882: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-22 12:27:04.614301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 5.84GiB
2019-06-22 12:27:04.614320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-22 12:27:05.246101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-22 12:27:05.246135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-06-22 12:27:05.246153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-06-22 12:27:05.246335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5616 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    word_attention_size, sentence_attention_size)
  File "/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/text_classification-pengming617/model/han/TrainModel.py", line 38, in trainModel
    articles, tags = processing.loadPracticeFile('data/train.txt')
  File "/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/text_classification-pengming617/model/han/Processing.py", line 19, in loadPracticeFile
    with open(filename, 'r', encoding='utf-8') as fr:
FileNotFoundError: [Errno 2] No such file or directory: 'data/train.txt'
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/text_classification-pengming617$

**Comment by pengming617** [comment]
the copus are in data directory.you can change the training file name.

**Comment by belle9217** [comment]
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: save_model/transformer/vocab.pickle : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\u
dca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process

when i use transformer model,there is a mistake.i don't know why.somebody who knows,i want to get help,thanks!

**Comment by pengming617** [comment]
the path of vocab.pickle may be incorrect. you should check it!




------------------ 原始邮件 ------------------
发件人: "belle9217"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 下午2:13
收件人: "pengming617/text_classification"<text_classification@noreply.github.com>; 
抄送: "彭明"<549639484@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [pengming617/text_classification] No such file or directory: 'data/train.txt'  OR which step I missed？ (#2)




tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: save_model/transformer/vocab.pickle : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\u
 dca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
 ; No such process
 
when i use transformer model,there is a mistake.i don't know why.somebody who knows,i want to get help,thanks!
